### ISSUE TITLE
AttributeError: function 'alcGetStringiSOFT' not found

### ISSUE THREAD

**Issue by the-byte-bender** [Sysop-Delco/OpenAL-PyLite#1]
Hello,

I renamed and coppied OpenAL32.dll from the link in the readme exactly as instructed, and everything should be OK. However, when I transfer the dll into one of the examples and try to execute it...

```

Traceback (most recent call last):
  File "C:\Users\ahmed\projects\OpenAL-PyLite\Examples\3D_Audio\OpenAL_3D.py", line 1, in <module>
    from openal import *
  File "C:\Users\ahmed\projects\OpenAL-PyLite\Examples\3D_Audio\openal.py", line 1966, in <module>
    alc = lib_alc()
  File "C:\Users\ahmed\projects\OpenAL-PyLite\Examples\3D_Audio\openal.py", line 760, in __init__
    self.alcGetStringiSOFT = self._lib.alcGetStringiSOFT
  File "C:\users\ahmed\python\lib\ctypes\__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "C:\users\ahmed\python\lib\ctypes\__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'alcGetStringiSOFT' not found

```

As a result, I cannot use it because importing it would result in the same error.

**Comment by Sysop-Delco** [comment]
Do you already have OpenAL installed?

There are two versions, regular OpenAL which is no longer updated, and OpenAL Soft which is. When regular OpenAL is installed it applies system pathing so if you try to import OpenAL, it will always default to that version whenever you try to import it, triggering this kind of error because its looking for OpenAL Soft bindings that it doesn't have. To fix it, either overwrite your OpenAL install with OpenAL Soft, which OpenAL Soft comes with instructions on how to do, or simply uninstall your existing OpenAL.

------- Original Message -------

**Comment by the-byte-bender** [comment]
Hello,
I have removed the old open al instelation I have, properly placed the new dll's alongside the script and renamed correctly, however, I get:

```
FileNotFoundError: Could not find module 'OpenAL32.dll' (or one of its dependencies). Try using the full path with constructor syntax.

```

I'm really not sure what to do specially when on the same setup the executable that come's with openal-soft that inform's you if you installed stuff correctly work's and reports everything is ok.

**Comment by the-byte-bender** [comment]
Update: I solved the issue about not finding the file by loading the dll using: 

```

        self._lib = ctypes.CDLL(os.path.realpath('OpenAL32.dll'))

```

Will keep the issue open in case you want to discuss anything or close it with a commit implementing that fix

**Comment by ashleygrobler04** [comment]
Hi there. I had the same issue that @Meatbag93 had. The fix he mentioned appears to be the best solution now.

**Comment by Sysop-Delco** [comment]
If I recall python 3 does not load DLL's by default as a security measure, so you'll need to ensure its in your current working directory, and add that directory to the DLL list for it to load it.

```
import os
os.add_dll_directory(os.getcwd())
from openal import *
```

**Comment by Sysop-Delco** [comment]
Python 3 changed up [loading DLL's](https://docs.python.org/3.8/whatsnew/3.8.html#bpo-36085-whatsnew) to be a bit more secure, specifically:

> DLL dependencies for extension modules and DLLs loaded with [ctypes](https://docs.python.org/3.8/library/ctypes.html#module-ctypes) on Windows are now resolved more securely. Only the system paths, the directory containing the DLL or PYD file, and directories added with [add_dll_directory()](https://docs.python.org/3.8/library/os.html#os.add_dll_directory) are searched for load-time dependencies. Specifically, PATH and the current working directory are no longer used, and modifications to these will no longer have any effect on normal DLL resolution. If your application relies on these mechanisms, you should check for [add_dll_directory()](https://docs.python.org/3.8/library/os.html#os.add_dll_directory) and if it exists, use it to add your DLLs directory while loading your library. Note that Windows 7 users will need to ensure that Windows Update KB2533623 has been installed (this is also verified by the installer).

I've seen other mention of using an absolute path in lieu of add_dll_directory or set_default_dll_directories for versions that don't support it. So i'll implement a check for both and clean up the examples. If there's further issues, let me know and we'll revisit the issue.

**Comment by the-byte-bender** [comment]
Hello,

I have did as you instructed - removed the instelation of openAL I already have. But now it is complaining about OpenAL32.dll or one of it's dependincies is missing even though I am 100% sure the dll is in the same folder as the script. Tried with both the 32-bit and 64-bit version of the dll, both renamed to OpenAL32.dll of corse, but no luck

I'm quite confused, any tips?

----- Original Message -----
From: Sysop-Delco ***@***.***>
To: Sysop-Delco/OpenAL-PyLite ***@***.***>
Cc: Meatbag93 ***@***.***>,  Author ***@***.***>
Date: Tue, 06 Sep 2022 21:03:32 -0700
Subject: Re: [Sysop-Delco/OpenAL-PyLite] AttributeError: function 'alcGetStringiSOFT' not found (Issue #1)

> Do you already have OpenAL installed?
> 
> 
> 
> There are two versions, regular OpenAL which is no longer updated, and OpenAL Soft which is. When regular OpenAL is installed it applies system pathing so if you try to import OpenAL, it will always default to that version whenever you try to import it, triggering this kind of error because its looking for OpenAL Soft bindings that it doesn't have. To fix it, either overwrite your OpenAL install with OpenAL Soft, which OpenAL Soft comes with instructions on how to do, or simply uninstall your existing OpenAL.
> 
> 
> 
> ------- Original Message -------
>

**Comment by Sysop-Delco** [comment]
Try checking what your current working directory is.
